[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.69"
wasm-bindgen="0.2"
md-5 = "0.9.0"
regex = "1.10.4"
sha1 = "0.10.6"

[lib]
crate-type = ["cdylib"]
